### ISSUE TITLE
Controls does not work on android

### ISSUE THREAD

**Issue by Arkan4ik** [criszz77/react-native-media-console#1]
Controls does not work on android. Can't stop or play video. Also faced problem when a lot of videos it has autoplay mode. I can't find how to disable it from props.

**Comment by criszz77** [comment]
@Arkan4ik thank you for raising the issue.

Will check it out this weekend. Would be very helpful if you could provide me with more info, like react,  react native, react-native-video versions that you’re using, etc.

 An example repo would help me a lot. If I can’t reproduce the issue, I’m not sure what to fix.

**Comment by criszz77** [comment]
Closing this as it can not be reproduced.
