### ISSUE TITLE
Adding showHours prop adds an extra letter in the time stamp

### ISSUE THREAD

**Issue by esegebart** [criszz77/react-native-media-console#12]
The showDuration prop works perfectly.

![image](https://user-images.githubusercontent.com/36378900/189207246-3159a565-7afd-44c9-90a4-c475db9ed184.png)

When I add the showHours prop, it shows this: 

![image](https://user-images.githubusercontent.com/36378900/189207355-f7d4644a-c4c8-4879-84b3-4f15fa2872b3.png)

**Comment by criszz77** [comment]
I could reproduce this. 

Here is where we calculate the time: https://github.com/criszz77/react-native-media-console/blob/master/src/utils.ts#L45-L76

Should be an easy fix.

**Comment by esegebart** [comment]
Well I will give it a shot! :)

**Comment by esegebart** [comment]
![image](https://user-images.githubusercontent.com/36378900/189209274-433405ee-ac8a-4b5f-bcb9-6b36b91323ac.png)

It would be this right here, right? Should be a zero?

**Comment by criszz77** [comment]
After you fork the repo and make your changes you will have to run `yarn prepare`. You can test it by running `yarn add [path to the forked repo]` in your app project (be sure to delete `node_modules` from forked repo). An easy way to get the path is to right click on the forked repo folder, press `Option` and keep it pressed, then select `Copy react-native-media-console as Pathname`.

If you run into issues, let me know, I'll be more than happy to help.

> It would be this right here, right? Should be a zero where the "a]" is?
I tested it and it seems to work, however, I don't have a video that long to test 🙈

**Comment by esegebart** [comment]
@criszz77 Awesome!!!

**Comment by criszz77** [comment]
Haha thank you! I am very happy as well :D
