### ISSUE TITLE
ability to customize openFullScreen button

### ISSUE THREAD

**Issue by coldSeattle** [criszz77/react-native-media-console#24]
<img width="283" alt="Снимок экрана 2022-10-05 в 00 35 49" src="https://user-images.githubusercontent.com/56102448/193921960-01804fd9-e64e-4c4a-a9e7-06286547c977.png">

**Comment by criszz77** [comment]
Hello @coldSeattle 

It is planned it a future version to have the ability to customise all the icons, as well as passing them styles. Unfortunately, I dont think it will be soon enough.

**Comment by coldSeattle** [comment]
thanks for answer!
