### ISSUE TITLE
ability change video time by clicking on duration tab like in youtube

### ISSUE THREAD

**Issue by coldSeattle** [criszz77/react-native-media-console#25]
like in video

https://user-images.githubusercontent.com/56102448/193922657-64367060-52b6-4906-9a85-6c5a0ab95db0.mov

**Comment by coldSeattle** [comment]
any comments from contributor ?

**Comment by criszz77** [comment]
Would be a very nice thing to have, but unfortunately, I'm the only maintainer and I don't think I will have time to look into it until December. :(

**Comment by coldSeattle** [comment]
well, okay, thanks for answer!
