### ISSUE TITLE
Issue with bottom notch and progress bar ( with fix included )

### ISSUE THREAD

**Issue by nrcaz** [criszz77/react-native-media-console#28]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-media-console@2.0.1` for the project I'm working on.

Issue ( the notch is not taken into account for the progress bar )
<img width="250" alt="Screenshot 2022-10-28 at 11 58 09" src="https://user-images.githubusercontent.com/45340504/202244658-f2644f3e-712c-4a23-b915-aa211c61729f.png">

fixed
<img width="250" alt="Screenshot 2022-10-28 at 11 58 43" src="https://user-images.githubusercontent.com/45340504/202244587-3d49e3f4-f6ec-4148-bf8c-1d283af09def.png">

Here is the diff that solved my problem:

```diff
index 6d4dce3..e31f0b6 100644
--- a/node_modules/react-native-media-console/src/components/BottomControls.tsx
+++ b/node_modules/react-native-media-console/src/components/BottomControls.tsx
@@ -2,10 +2,11 @@ import React, {Dispatch, SetStateAction} from 'react';
 import {
   Animated,
   ImageBackground,
-  SafeAreaView,
   StyleSheet,
   GestureResponderHandlers,
+  View,
 } from 'react-native';
+import { SafeAreaView } from 'react-native-safe-area-context';
 import {Timer} from './Timer';
 import {Title} from './Title';
 import {NullControl} from './NullControl';
@@ -114,12 +115,12 @@ export const BottomControls = ({
         source={require('../assets/img/bottom-vignette.png')}
         style={[styles.column]}
         imageStyle={[styles.vignette]}>
-        <SafeAreaView style={[styles.row, _styles.bottomControlGroup]}>
+        <View style={[styles.row, _styles.bottomControlGroup]}>
           {timerControl}
           <Title title={title} />
           {fullscreenControl}
-        </SafeAreaView>
-        <SafeAreaView style={styles.seekBarContainer}>
+        </View>
+        <SafeAreaView style={styles.seekBarContainer} edges={['bottom']}>
           {seekbarControl}
         </SafeAreaView>
       </ImageBackground>
@@ -139,6 +140,5 @@ const _styles = StyleSheet.create({
     justifyContent: 'space-between',
     marginLeft: 12,
     marginRight: 12,
-    marginBottom: 0,
   },
 });
```

Also adding this peer dependency in `package.json`
```
"react-native-safe-area-context": ">=3.0.0"
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by nrcaz** [comment]
Sure

**Comment by criszz77** [comment]
I just checked it and I really can't reproduce it. With the right styles, I'm sure you can achieve the wanted result. If you provide me with a reproduction repository, I'll reopen the issue again.

<img width="401" alt="image" src="https://user-images.githubusercontent.com/55203625/213782548-a789e60e-256b-477f-b9d1-60a59d3d078d.png">
