### ISSUE TITLE
Request: prop for hiding the rewind + fast forward controls without hiding play/pause

### ISSUE THREAD

**Issue by sam1463** [criszz77/react-native-media-console#45]
TItle sums it up. I have an example [here](https://github.com/criszz77/react-native-media-console/compare/master...sam1463:react-native-media-console:master) but thought I'd open an issue to get feedback before opening a PR. I added it as a separate prop from disablePlayPause for backwards compatibility (instead of changing that prop to only operate on the play/pause button)

**Comment by criszz77** [comment]
Yup, looks good. Maybe `disableSeekButtons`? Really can't decide on a good name for it

**Comment by criszz77** [comment]
Let me know if you need help, I still didn't prepare a contribution guide
