### ISSUE TITLE
Property 'source' does not exist on type 'IntrinsicAttributes & VideoPlayerProps'.ts(2322)

### ISSUE THREAD

**Issue by dklymenk** [criszz77/react-native-media-console#5]
Hello and thank you for this great library.

I couldn't exactly figure out why, but typescript complains at me for using the `source` prop.

![DeepinScreenshot_select-area_20220519004825](https://user-images.githubusercontent.com/64093836/169161495-c985639a-0356-444f-adcc-710f6312eaa5.png)

Here is the line that causes the issue for me, in case it helps:
https://github.com/dklymenk/warcrime/blob/f1ead22ec05eb2d48f3419c4095bdc136196d7ed/app/screens/report/report-screen.tsx#L112

**Comment by criszz77** [comment]
Hello @dklymenk.

Thank you for pointing out this issue. Will fix it as soon as possible.

**Comment by dklymenk** [comment]
It turned out that the issue is not related to this library. But I simply had to install the types package for underlying library.
Installing `@types/react-native-video` fixes the issue.
